export const relevant_links = [
  { url: "https://www.bridgestoscience.org/", label: "Home" },
  { url: "https://www.bridgestoscience.org/about/", label: "About Us" },
  { url: "https://www.bridgestoscience.org/programs/", label: "Programs Overview" },
  { url: "https://www.bridgestoscience.org/get-involved/", label: "Get Involved" },
  { url: "https://www.bridgestoscience.org/workshops/", label: "Workshops" },
  { url: "https://www.bridgestoscience.org/classroom-toolkit/", label: "Classroom Toolkit" },
  { url: "https://www.bridgestoscience.org/guest-speaker/", label: "Guest Speaker Info" },
  { url: "https://www.bridgestoscience.org/internship/", label: "Internship Info" },
  { url: "https://www.bridgestoscience.org/contact-us/", label: "Contact Us" },
  { url: "https://www.bridgestoscience.org/blog/", label: "Blog" },
  { url: "https://www.bridgestoscience.org/gallery/", label: "Gallery" },
  { url: "https://www.bridgestoscience.org/houston-science-festival-faq/", label: "Houston Science Festival FAQ" },
  { url: "https://www.bridgestoscience.org/bridges-to-science-named-2022-top-rated-nonprofit/", label: "2022 Top-Rated Nonprofit Announcement" },
  { url: "https://www.bridgestoscience.org/first-day-of-our-2022-coding-club-boot-camp/", label: "2022 Coding Club Boot Camp Day 1" },
  { url: "https://www.bridgestoscience.org/advice-to-new-home-educators/", label: "Advice to New Home Educators" },
  { url: "https://www.bridgestoscience.org/how-bridges-to-science-got-its-start/", label: "Organization Origin Story" },
  { url: "https://www.bridgestoscience.org/stem-youth-coaches/", label: "STEM Youth Coaches" },
  { url: "https://www.bridgestoscience.org/wp-content/uploads/2022/07/Rosa-Aristy-Speaker-Sheet.pdf", label: "Rosa Aristy Speaker Sheet (PDF)" },
  { url: "https://docs.google.com/forms/d/e/1FAIpQLScq24nlmhkl1GN9bQA2Tq6gdbIRotinsjrYcrFWdRpfyviKjw/viewform", label: "Coding Club 2022-2023 Form" },
  { url: "https://docs.google.com/forms/d/e/1FAIpQLSeY6qBK3GtnZ47-iv4MQKKdeUupByLcUaG6EZBPKBgRbptO6w/viewform", label: "Houston Math Circle 2022-2023 Form" },
  { url: "https://secure.givelively.org/donate/bridges-to-science", label: "Donate Page" },
  { url: "https://www.facebook.com/bridgestoscience/", label: "Facebook Page" },
  { url: "https://www.instagram.com/bridgestoscience/", label: "Instagram Page" },
  { url: "https://www.linkedin.com/company/bridgestoscience/", label: "LinkedIn Page" },
  { url: "https://twitter.com/bridges2science", label: "Twitter Page" },
  { url: "mailto:info@bridgestoscience.org", label: "Email Contact" },
  { url: "https://www.thehersheycompany.com/en_us/home/sustainability/sustainability-focus-areas/youth/heartwarming-project.html", label: "Hershey Heartwarming Project" },
  { url: "https://velaedfund.org/", label: "VELA Education Fund" },
  { url: "https://tyan.tamu.edu/portfolio-items/bridges-to-science/", label: "Texas Youth Action Network Feature" },
  { url: "https://canaryacademyonline.org/", label: "Canary Academy Online" },
  { url: "https://www.autmhq.org/post-1/autmhq-is-building-new-bridges-with-bridges-to-science", label: "AUTMHQ Partnership Article" },
  { url: "https://twitter.com/kennedydee/status/1542073237785530369?s=21&t=UHyQqnvvEI0gl8f5rA9_Pw", label: "Twitter Mention by Kennedy Dee" },
  { url: "https://docs.google.com/spreadsheets/d/1E-HjVbBDr0K3kdBOPsa782ZWLzQnK8WovifXLHLY9JY/edit?gid=0#gid=0", label: "Bridges to Science Onboarding Volunteer Checklist"},
];
